# Generated by Django 4.1.7 on 2023-02-23 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_booking_date_processing_booking_is_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Thats wrong number, let's try again", regex='/^\\+38\\d({3})\\d{3}\\d{2}\\d{2}$/')]),
        ),
    ]
