# Generated by Django 4.1.7 on 2023-02-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-date', 'time', 'user')},
        ),
    ]
