# Generated by Django 4.1.7 on 2023-02-24 11:45

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_gallery',
            name='photo',
            field=models.ImageField(default=1, upload_to=main_page.models.Photo_gallery.get_file_name),
        ),
    ]
